# Generated by Django 5.1.1 on 2024-09-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_document_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='hashtags',
        ),
    ]
