# Generated by Django 5.1.1 on 2024-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_document_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
